### PR TITLE
ENH: Pull upstream changes.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Pull upstream changes.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@jcfr @thewtex I have not checked building the upstream repo against ITK's master, but I guess this is likely to work seamlessly. If checking is required, let me know.

**Comment by thewtex** [comment]
Thanks for the update, @jhlegarreta !

We should wait until @jcfr has confirmed that Slicer is built with sufficiently new CMake, since this module is used inside Slicer.

**Comment by jcfr** [comment]
You can go ahead with the integration. For now, Slicer build with ITK 4.13 and the update of CMake version in Slicer will be done by the time we updated the version of ITK used.

**Comment by jcfr** [comment]
I also suggest we archive Slicer/itkMGHImageIO since most of the development is (or will be done) in the ITK fork.

What do you think ?

**Comment by jhlegarreta** [comment]
I'll try to check that this builds against the current ITK master today or tomorrow.

As for archiving `Slicer/itkMGHImageIO`. 👍 if the development will be done in the ITK fork.

Although my viewpoint may be biased since I am not a Slicer developer, the less sync work we need to do/the more immediate is to tell which is the *upstream* to be used in the ITK remote module, the better

**Comment by jhlegarreta** [comment]
I'v'e just tested locally (Win 10, MSVC 2015 CE) that `Slicer/itkMGHImageIO` head builds OK against the latest `ITK master`. In fact the 8c1e4eaa6b77a755173e27d738fbe1f49c96ec83 commit hash was incorporated to the MGHIO.remote.cmake in topic:
http://review.source.kitware.com/#/c/23176/

Thus, nothing advises against merging this. The **decision on freezing** `Slicer/itkMGHImageIO` in favor of `InsightSoftwareConsortium/itkMGHImageIO` **is left only**.

**Pull request merged**
