### PR TITLE
Fix test failure related to issue #7

### PR DESCRIPTION
**Pull request by hjmjohnson**
@jcfr This set of patches fixes MGHIO to resolve a bug when writing MGH files to disk.  This was described in issue #7 

The bug only presented itself when the transpose of the DirectionCosine was different.

The test suite was fortified, and improved to demonstrate the bug, and then the code was re-written to allow for the fortified tests to pass.

### CODE REVIEW

**Comment by pieper** [comment]
I read through the changes and they look great to me - I did not try building but +1 for merging unless anyone objects.

**Comment by jcfr** [comment]
Thanks @hjmjohnson :+1: 

As discussed on the mailing list (see [here](http://slicer-devel.65872.n3.nabble.com/Transition-to-ITK-MGHIO-filter-td4034495.html)), Slicer should be updated to use this repository instead of the code living in [Slicer/Libs/MGHImageIO](https://github.com/Slicer/Slicer/tree/master/Libs/MGHImageIO). 

Out of curiosity, do you have a Slicer topic for this.

If not, I can work on this later next week.

**Comment by hjmjohnson** [comment]
@jcfr I'm working on a topic for this.  

Ran into trouble because BRAINSTools had some logic to allow it to utilize the slicer base MGHIO dynamic library, but that code was hard coded conditional logic that is no longer needed when using the ITK version.

Integrating into ITK allowed extensive testing of reading/writing, and that unconvered bugs (in both ITK and Slicer versions) that needed fixing.

I think I will have pull requests soon for all of these fixes.

I need time to test.

Hans

**Comment by jcfr** [comment]
:+1:  Tres bien. Will then wait for the Slicer PR.

**Comment by pieper** [comment]
Thanks for doing this Hans!

**Pull request merged**
