### PR TITLE
ENH: Require cmake minimum version to be 3.9.5.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Require CMake minimum version to be 3.9.5 following ITKv5 requiring
C++11:
https://discourse.itk.org/t/minimum-cmake-version-update/585

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks @jhlegarreta 

After agreeing an also updating the version of CMake in Slicer, we will go ahead with integrating.

xref https://discourse.slicer.org/t/updating-minimum-required-version-of-cmake-to-3-9-5/1873

**Comment by hjmjohnson** [comment]
@jcfr.  This will affect the ability of ITKv5 to build.  We plan to update ITK requirement to 3.9.5 starting today, so this will be necessary for building this module with ITKv5 starting today.  

Also, we plan to require C++11 starting next Friday.  There will be another pull request at that point.

**Comment by hjmjohnson** [comment]
@jcfr . Hi JC.   Why does the integration of this need to wait for slicer to be updated?  

SuperBuild/External_ITKv4.cmake:      -DModule_MGHIO:BOOL=ON

Changing the itkMGHImageIO directory only affects the external module of ITK.  Slicer will not be affected until it updates the ITK version.

I think this should be safe to merge now.

**Comment by jcfr** [comment]
> Why does the integration of this need to wait for slicer to be updated?

Matter of bandwidth. Since this is not in the critical path, I didn't have a chance to get to it.

> Changing the itkMGHImageIO directory only affects the external module of ITK. Slicer will not be affected until it updates the ITK version.

👍  for moving this forward.

**Pull request merged**
